name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['14', '16', '18']
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm ci

      - name: Seyup Docker Environment
        run: |
          docker pull wordpress
          docker pull mysql:5.7
          docker pull hello-world

      - name: Run tests
        run: npm run coverage

      - name: Uplode coverage
        if: ${{ matrix.node-version == '16.x' }}
        uses: codecov/codecov-action@v3
        with:
          directory: ./coverage
          fail_ci_if_error: true

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version: 16

      - name: Install Dependencies
        run: npm ci

      - name: Run Linter
        run: npm run lint

  release:
    needs: [lint, test]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version: 16

      - name: Install Dependencies
        run: npm ci

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release@latest
