name: Test

on: 
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['10.x', '12.x', '14.x']
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Get npm cache directory path
        id: npm-cache-dir-path
        run: echo "::set-output name=dir::$(npm config get cache)"

      - uses: actions/cache@v2
        id: npm-cache
        with:
          path: ${{ steps.npm-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.lock') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install Dependencies
        run: npm ci

      - name: Seyup Docker Environment
        run: |
          docker pull wordpress
          docker pull mysql:5.7
          docker pull hello-world

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run tests
        run: npm run coverage

      - name: Uplode coverage
        if: ${{ matrix.node-version == '14.x' }}
        uses: codecov/codecov-action@v1
        with:
          directory:  ./coverage
          fail_ci_if_error: true
